sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "d2EazkWEnI8JGz2EzxsGyfhdDjTQILQRMylFq9qZHBtaI8m1m9qg382xCE0g0UMsPJpo3t8GKI5jLNCOMxVaz4kX2uSQqT+mdR9R0w9/AJq4rkUFOlJPnEQIZ6ITj3U8wpeYM5jt1hnSAXpsZcPtA68OiFho442cl1rU+ObUPxLrEWAR4ICHW6rKVw8v8rJBC7FtXwWa2ZYaez/L8v5IN4LTgNz0GPTQBEwk1c5phRWNGf9Og9UjlzkmSNuIH4oKAi61NKua4lAPYZYfKWiioF4u2HmxvOjtX5mRolAs2J1g7eO+UQHDKltZaSiJR180U864l4sFXu9J45jt3KegMLrglXoaSnULD/DFbbDfgm2AL/yDJsQoWVu453ys08hIqSpYLZZoJep5U20fhhhBMxdfNOWxRUptuqMr/OUq7ONwpIKAb6k0pNvyyL8i+BRBpqhpseHVQx+j5KF7v2qpaOYKO0qeCnzu8VOLxwiM1BRyJ7OH3hzpdFtg5mfYIS/riK1PhXRLscvI2fNYj5VXwv+ahHpSb+WHp+Rn5ykvcef9JAqBAW2n2+X5WsLA6YzT2wK7e/wRdTz2lrxptuv/PJWOgVPI+JejeCXzbyX1LqkSHxVEQQoXQYoHcnDnpLJO0ryoRUE1Hdh2gz8JMNJ16HKCL6nJuuTSV259Hn5aZ7g="
  - secure: "CD2FNDY0dLAkLofzbtxp9ie1hC1I9BREd3v7iL1Iai1G0NwY431K9AHrEFBIY3FzjY98MRuCYguQEjMAq9diZz8GCMLGqcwKw0OeetrtLmlPmiNcfVruYD6255K4NlbCGcwPQ5rpLpDALu+clZc+re4fiw5E1zgL9TYvqSDH5IsbKHa015YNPQl5/UX/MveubklofISQo9eP083fzzsVZfhmtdC3OTh83IMMYUTFuPa1cGqngmmsTpn/ufofKtF9rk/6nrn7AKgu8jVp42ydg5442lzxT8aJjHkruiljQmOAMAgBviXv1P8LgIxXh1nsjRlyg/kVNem4vivOy7iaxxMK876ubcc/lbRNpZBIwXTD1ZGN5TAhc5kvmiirgCE7U2bZlzCNbz1LUHpR6O4uIIcJ0/Q7wCDb2OJf9yQ/92XKLVVpRarnbLmFj2NVHtD8QKDK9nc2G/WUaWZmXDaSOCW5BWkNRm8KVUB8adtMwC+oHqjKROwCdwNSP9kO7s/jOhjoUy0XJk7B+ayUbfKU9M9GhITlTBTgKLVXjTGJErt0zOUgxkLifqoF2ypY5jDXRMtTGcpX8V/1mM0jq4KEwYYItyMnj2UZSxguA1rLg6WN3bw/56q0JQQvnTr0/Z88BbEyLMeD99ePHXJxp5ZVeq9ii36dUPaZEVyJTeCmb0k="
  - secure: "EXHVdwLexxFcu7tZjUhua8HcfS0t7VpiwtzYV3UM4CsuXGqpvBD/KNxyB1UQc4aqErXLkjrJ4gBNQdBklgulH0SL7ic0dlCsiCn2ecctmL/j02RxPV0PdfDiKHExjSFUGn4zQCybv7lua88GFCNMuP1U/JDdQd4AyHwhvSHHl5DNhToPzyHfoW2utnS7o2gbXjDGXA68l0zPVbgfUmp61Nsbfa1BaZFxYhl0Ctn1KrurlNP5SUVt+K5JR1/Djmcstmc0rdDUjvZuGj87Abu7D4MBWCeM1HRk3eguMtk99i2AEdiac4hyzr7BqEBtG1FrFoYuagvB3s65JRvE9hIxcgJjtKdj6refRYiKy4A6/hmsHmlDFeSaqqvsK1RROqyTtWIHD0rBeOQ3lItBdeoYKtx89NaOzwpe2CSVw9C5HJmdAc8Z7lGn1DdjewM9iIS+2x3LvW/blOov/BCi7Uu5tbMjmeWXgQW4t/YKMLOSDDf6bOWu9KdHsTiYAWURB2eK+yRyyN80psW23e6U7uA/NW204bXDRyYAqEXsxRUGjV9fBFXcy4LCtjwKxIKkOE+n9xVLsixMBsqoKxN0KQ+bvguC3VcIJ19bVcp0UrSI0Qu7qOutqaL9Wmk8VNfhJN4NILHrsDKyQ9jMo6XtPV7gYBbvBvVqaiAQ4NYfW9g8T/U="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
